trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: job1
  dependsOn: job2

  steps:
  - script: echo Job1 Hello, world, changed!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'

- job: job2
  dependsOn: job3

  steps:
  - script: echo Job2 Hello, world, changed!
    displayName: 'Run a one-line script'

- job: job3

  steps:
  - script: echo Job2 Hello, world, changed!
    displayName: 'Run a one-line script'